# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MER_Player' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MER_Player
pod 'Masonry'
  target 'MER_PlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
